### ISSUE TITLE
Reference for the Dirichlet change point model

### ISSUE THREAD

**Issue by BobZhangHT** [abuzarmahmood/teachables#1]
Hi Abuzar！Thank you very much for your nice tutorial notebook for change point detection problem.

When I read your notebook `dirichlet_changepoint_model.ipynb`, I felt very confused about rationale behind the construction of the matrix `weight_stack`. It is hard to interpret this part of codes into the mathematical definition for the Bayesian modelling, and I could not find the related information online about the mathematical formulation. 

```python
    # Weight stack to assign lambda's to point in time
    weight_stack = tt.nnet.sigmoid(idx[np.newaxis,:]-tau[:,np.newaxis])
    weight_stack = tt.concatenate([np.ones((1,length)),weight_stack],axis=0)
    inverse_stack = 1 - weight_stack[1:]
    inverse_stack = tt.concatenate([inverse_stack, np.ones((1,length))],axis=0)
    weight_stack = np.multiply(weight_stack,inverse_stack)
```

Therefore, it would be great if you could provide any references (e.g. academic articles) for this block of codes. Thank you so much!

**Comment by abuzarmahmood** [comment]
Hi, thanks for reaching out.
I don't think there is a statistical interpretation of that step, it's just a way of applying the generated emission and changepoint variable to generate a timeseries. I have more in-depth explanations in the links below. The notebooks from the github repo below break down the weight-stack construction more comprehensively (and the video is basically a walkthrough of the notebook). Feel free to reach out if you still have questions once you've been through these.

Good luck,
Abu


https://youtu.be/iwNju1o5yQo?si=PoPIer6rR_k8MfrP
https://github.com/abuzarmahmood/pymcon_bayesian_changepoint

**Comment by BobZhangHT** [comment]
Thank you so much for your prompt and detailed explanation!~

**Comment by abuzarmahmood** [comment]
Of course! I'm closing this issue then. Feel free to open it again if you have any other questions.
